module.exports = {
  plugins: ['stylelint-prettier', 'stylelint-order'],
  overrides: [
    {
      files: ['**/*.scss'],
      customSyntax: 'postcss-scss'
    }
  ],
  rules: {
    'no-empty-source': true,
    'prettier/prettier': true,
    'block-no-empty': true,
    'order/properties-order': [
      'scss-mixin',
      'content',

      // position

      'position',
      'z-index',
      'top',
      'bottom',
      'left',
      'right',

      'transform',
      'transform-box',
      'transform-origin',
      'transform-style',

      // position end

      // box
      'display',

      'table-layout',

      'vertical-align',

      'visibility',

      'flex',
      'flex-basis',
      'flex-direction',
      'flex-flow',
      'flex-grow',
      'flex-shrink',
      'flex-wrap',

      'justify-content',
      'justify-items',
      'justify-self',

      'align-content',
      'align-items',
      'align-self',
      'alignment-baseline',

      'order',

      'column-count',
      'column-fill',
      'column-gap',
      'column-rule',
      'column-rule-color',
      'column-rule-style',
      'column-rule-width',
      'column-span',
      'column-width',
      'columns',

      'grid',
      'grid-area',
      'grid-auto-columns',
      'grid-auto-flow',
      'grid-auto-rows',
      'grid-column',
      'grid-column-end',
      'grid-column-start',
      'grid-row',
      'grid-row-end',
      'grid-row-start',
      'grid-template',
      'grid-template-areas',
      'grid-template-columns',
      'grid-template-rows',

      'gap',

      'float',
      'float-defer',
      'float-offset',
      'float-reference',

      'width',
      'height',

      'min-width',
      'min-height',

      'max-width',
      'max-height',

      'max-block-size',
      'max-inline-size',
      'max-lines',
      'min-block-size',
      'min-inline-size',

      'margin',
      'margin-block',
      'margin-block-end',
      'margin-block-start',
      'margin-break',
      'margin-inline',
      'margin-inline-end',
      'margin-inline-start',
      'margin-left',
      'margin-right',
      'margin-top',
      'margin-bottom',
      'margin-trim',

      'padding',
      'padding-block',
      'padding-block-end',
      'padding-block-start',
      'padding-inline',
      'padding-inline-end',
      'padding-inline-start',
      'padding-left',
      'padding-right',
      'padding-top',
      'padding-bottom',

      'overflow',
      'overflow-anchor',
      'overflow-block',
      'overflow-clip-margin',
      'overflow-inline',
      'overflow-wrap',
      'overflow-x',
      'overflow-y',

      'scroll-behavior',
      'scroll-margin',
      'scroll-margin-block',
      'scroll-margin-block-end',
      'scroll-margin-block-start',
      'scroll-margin-bottom',
      'scroll-margin-inline',
      'scroll-margin-inline-end',
      'scroll-margin-inline-start',
      'scroll-margin-left',
      'scroll-margin-right',
      'scroll-margin-top',
      'scroll-padding',
      'scroll-padding-block',
      'scroll-padding-block-end',
      'scroll-padding-block-start',
      'scroll-padding-bottom',
      'scroll-padding-inline',
      'scroll-padding-inline-end',
      'scroll-padding-inline-start',
      'scroll-padding-left',
      'scroll-padding-right',
      'scroll-padding-top',
      'scroll-snap-align',
      'scroll-snap-stop',
      'scroll-snap-type',
      'scrollbar-color',
      'scrollbar-gutter',
      'scrollbar-width',

      'box-sizing',
      'clear',

      // typo
      'font',
      'font-family',
      'font-feature-settings',
      'font-kerning',
      'font-language-override',
      'font-optical-sizing',
      'font-palette',
      'font-size',
      'font-size-adjust',
      'font-stretch',
      'font-style',
      'font-synthesis',
      'font-synthesis-small-caps',
      'font-synthesis-style',
      'font-synthesis-weight',
      'font-variant',
      'font-variant-alternates',
      'font-variant-caps',
      'font-variant-east-asian',
      'font-variant-emoji',
      'font-variant-ligatures',
      'font-variant-numeric',
      'font-variant-position',
      'font-variation-settings',
      'font-weight',

      'line-height',

      'letter-spacing',

      'text-align',
      'text-align-all',
      'text-align-last',
      'text-combine-upright',
      'text-decoration',
      'text-decoration-color',
      'text-decoration-line',
      'text-decoration-skip',
      'text-decoration-skip-box',
      'text-decoration-skip-ink',
      'text-decoration-skip-inset',
      'text-decoration-skip-self',
      'text-decoration-skip-spaces',
      'text-decoration-style',
      'text-decoration-thickness',
      'text-edge',
      'text-emphasis',
      'text-emphasis-color',
      'text-emphasis-position',
      'text-emphasis-skip',
      'text-emphasis-style',
      'text-group-align',
      'text-indent',
      'text-justify',
      'text-orientation',
      'text-overflow',
      'text-shadow',
      'text-space-collapse',
      'text-space-trim',
      'text-spacing',
      'text-transform',
      'text-underline-offset',
      'text-underline-position',
      'text-wrap',

      'white-space',
      'word-break',
      'word-spacing',
      'word-wrap',
      'writing-mode',

      'color',
      'color-adjust',
      'color-interpolation-filters',
      'color-scheme',

      'caret-color',
      'caret-shape',

      // decoration

      'background',
      'background-attachment',
      'background-blend-mode',
      'background-clip',
      'background-color',
      'background-image',
      'background-origin',
      'background-position',
      'background-repeat',
      'background-size',

      'object-fit',
      'object-position',

      'stroke',
      'stroke-align',
      'stroke-alignment',
      'stroke-break',
      'stroke-color',
      'stroke-dash-corner',
      'stroke-dash-justify',
      'stroke-dashadjust',
      'stroke-dasharray',
      'stroke-dashcorner',
      'stroke-dashoffset',
      'stroke-image',
      'stroke-linecap',
      'stroke-linejoin',
      'stroke-miterlimit',
      'stroke-opacity',
      'stroke-origin',
      'stroke-position',
      'stroke-repeat',
      'stroke-size',
      'stroke-width',

      'fill',
      'fill-break',
      'fill-color',
      'fill-image',
      'fill-opacity',
      'fill-origin',
      'fill-position',
      'fill-repeat',
      'fill-rule',
      'fill-size',

      'clip',
      'clip-path',
      'clip-rule',

      'border',
      'border-bottom',
      'border-bottom-color',
      'border-bottom-left-radius',
      'border-bottom-right-radius',
      'border-bottom-style',
      'border-bottom-width',
      'border-boundary',
      'border-collapse',
      'border-color',
      'border-end-end-radius',
      'border-end-start-radius',
      'border-image',
      'border-image-outset',
      'border-image-repeat',
      'border-image-slice',
      'border-image-source',
      'border-image-width',
      'border-inline',
      'border-inline-color',
      'border-inline-end',
      'border-inline-end-color',
      'border-inline-end-style',
      'border-inline-end-width',
      'border-inline-start',
      'border-inline-start-color',
      'border-inline-start-style',
      'border-inline-start-width',
      'border-inline-style',
      'border-inline-width',
      'border-left',
      'border-left-color',
      'border-left-style',
      'border-left-width',
      'border-right',
      'border-right-color',
      'border-right-style',
      'border-right-width',
      'border-spacing',
      'border-start-end-radius',
      'border-start-start-radius',
      'border-style',
      'border-top',
      'border-top-color',
      'border-top-left-radius',
      'border-top-right-radius',
      'border-top-style',
      'border-top-width',
      'border-width',
      'border-radius',

      'opacity',

      'box-shadow',

      'filter',

      // decoration end

      // animations

      'animation',
      'animation-delay',
      'animation-direction',
      'animation-duration',
      'animation-fill-mode',
      'animation-iteration-count',
      'animation-name',
      'animation-play-state',
      'animation-timing-function',

      'transition',
      'transition-delay',
      'transition-duration',
      'transition-property',
      'transition-timing-function',

      // animations end

      // other
      'cursor',
      'appearance',
      'resize',
      'outline',
      'user-select',
      'outline-color',
      'outline-offset',
      'outline-style',
      'outline-width'
    ]
  }
};
